In [1]:
import numpy as np

In [3]:
x = np.array(
    [[1, 6, 8, 0],
    [33, 2, 3, 5],
    [1, 6, 6, 7],
    [2, 9, 8, 4],
    [5, 6, 9, 6],
    [32, 13, 0, 2]])
x

array([[ 1,  6,  8,  0],
       [33,  2,  3,  5],
       [ 1,  6,  6,  7],
       [ 2,  9,  8,  4],
       [ 5,  6,  9,  6],
       [32, 13,  0,  2]])

In [4]:
x.shape

(6, 4)

In [6]:
x.ndim

2

In [7]:
y = np.array(
    [[1, 0, 1, 0],
    [0, 1, 0,1]])
y

array([[1, 0, 1, 0],
       [0, 1, 0, 1]])

In [11]:
# y(2*4) = z( Transpose( W(a? * b?) ) * X(6*4) + b(1*1) )
# a = 6
# b = 2 --> Should be equal to first dimension of y
W_dim = (6, 2) # the output of hidden dim would be (6, 2)

In [12]:
W = np.full(W_dim, 0.01)
b = 0.01
W

array([[0.01, 0.01],
       [0.01, 0.01],
       [0.01, 0.01],
       [0.01, 0.01],
       [0.01, 0.01],
       [0.01, 0.01]])

In [13]:
WT = np.transpose(W)
WT

array([[0.01, 0.01, 0.01, 0.01, 0.01, 0.01],
       [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]])

In [23]:
tmp = np.dot(WT, x) + 0.01
tmp

array([[0.75, 0.43, 0.35, 0.25],
       [0.75, 0.43, 0.35, 0.25]])

In [25]:
def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

In [26]:
yhat = sigmoid(tmp)
yhat

array([[0.6791787 , 0.60587367, 0.58661758, 0.5621765 ],
       [0.6791787 , 0.60587367, 0.58661758, 0.5621765 ]])

In [27]:
err = y - yhat
err

array([[ 0.3208213 , -0.60587367,  0.41338242, -0.5621765 ],
       [-0.6791787 ,  0.39412633, -0.58661758,  0.4378235 ]])

In [28]:
loss = np.linalg.norm(err)
loss

1.4523654926672458

In [30]:
def nn_output_loss(x, W, b, y_truth):
    WT = np.transpose(W)
    tmp = np.dot(WT, x) + 0.01

    yhat = 1.0 / (1.0 + np.exp(-x))
    err = y - yhat
    loss = np.linalg.norm(err)

    return yhat, loss
    

    

In [32]:
nn_output_loss(x, W, b, y)

ValueError: operands could not be broadcast together with shapes (2,4) (6,4) 

In [ ]:

# need to fix but maybe another time