In [2]:
import numpy as np

def median_of_array_columns(numbers):
    return np.median(numbers, axis=0)
    

In [3]:
mark2 = np.asarray([55, 88, 78, 90, 79, 94]).reshape(2, -1)
print('%d' % median_of_array_columns(mark2).shape[0])

3


In [4]:
mark2

array([[55, 88, 78],
       [90, 79, 94]])

In [6]:
median_of_array_columns(mark2)

array([72.5, 83.5, 86. ])

In [7]:
median_of_array_columns(mark2).shape

(3,)

In [8]:
	
marks = np.asarray([2010522, 2010733, 2010998, 2010135, 2010755, 2010648, 2011840, 2010541, 2010254, 2010691, 2004011, 2010248, 2008576, 2009249, 1900723, 2009490, 2003251, 2010290]).reshape((-1, 3))
print('%d' % median_of_array_columns(marks).shape[0])

3


In [9]:
marks

array([[2010522, 2010733, 2010998],
       [2010135, 2010755, 2010648],
       [2011840, 2010541, 2010254],
       [2010691, 2004011, 2010248],
       [2008576, 2009249, 1900723],
       [2009490, 2003251, 2010290]])

In [11]:
median_of_array_columns(marks)

array([2010328.5, 2009895. , 2010272. ])

In [13]:
	
np.random.seed(2)
marks = np.random.randint(0, 101, 50).reshape((10, -1))
print(marks)
print(median_of_array_columns(marks))
print('%.2f' % median_of_array_columns(marks)[3])

[[40 15 72 22 43]
 [82 75  7 34 49]
 [95 75 85 47 63]
 [31 90 20 37 39]
 [67  4 42 51 38]
 [33 58 67 69 88]
 [68 46 70 95 83]
 [31 66 80 52 76]
 [50  4 90 63 79]
 [49 39 46  8 50]]
[49.5 52.  68.5 49.  56.5]
49.00


In [14]:
import numpy as np


def policy(p1, p2, p3, p4=0.5):
    # p1, p2, p3 are, respectively, the probabilities of choosing between 1, 2, and 3
    # the default value for p4 should be 0.5
    # action equals 1 with probability p1, 2 with probability p2, and 3 with probability p3
    action = np.random.choice([1, 2, 3], p=[p1, p2, p3])
    # Depending on the value of 'action', we choose one of the following options:
    # if action is 1: return action1()
    # if action is 2: return action2()
    # if action is 3: make a choice between returning action1() (with probability p4) or action2()
    #   i.e.: return action1() with probability p4, and action2() otherwise

    ## YOUR CODE HERE
    if action == 1:
        return action1() # we should add () to call action1 function
    elif action == 2:
        return action2()
    else:
        return np.random.choice([action1(), action2()], p=[p4, 1-p4])



def action1(p=0.2):
    # Return 0 with probability p and 1 otherwise
    # the default value for p should be 0.2
    
    ## YOUR CODE HERE
    return np.random.choice([0, 1], p=[p, 1-p])
    

def action2(p=0.9):
    # Return 3 with probability p and -5 otherwise
    # the default value for p should be 0.9
    
    ## YOUR CODE HERE
    return np.random.choice([3, -5], p=[p, 1-p])



In [15]:
	
np.random.seed(4)
# Check default value for p1
pulls = [action1() for _ in range(20000)]
print('%.3f' % np.mean(pulls))

0.794


In [16]:
	
np.random.seed(4)
# Check default value for p2
pulls = [action2() for _ in range(20000)]
print('%.3f' % np.mean(pulls))

2.192


In [17]:
	
# Check default value for p4
np.random.seed(3)
pulls = [policy(0, 0, 1) for _ in range(20000)]
print('%.3f' % np.mean(pulls))

1.501


In [18]:
# Changing default value for p4
np.random.seed(3)
pulls = [policy(0, 0, 1, 0.9) for _ in range(20000)]
print('%.3f' % np.mean(pulls))

0.944
